name: lint-pr

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install commitlint
        run: yarn add global @commitlint/cli @commitlint/config-conventional

      - name: Configure commitlint
        run: echo "module.exports = {extends${{':'}} ['@commitlint/config-conventional']}" > commitlint.config.js

      - name: Lint PR
        run: echo ${{ github.event.pull_request.title }}
